name: Just Deploy

on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    needs: []
    runs-on: ubuntu-latest

    steps:
      - run: pwd && ls
      - run: cd /home/runner/work/the-vivi-project/code && ls
      - name: Publish to surge.sh
        # You may pin to the exact commit or the version.
        # uses: dswistowski/surge-sh-action@c09463ed5222f67391260fa806240d4e464743d0
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          # your surge.sh domain to deploy
          domain: the-vivi-project.surge.sh
          # surge.sh login
          login: ${{ secrets.SURGE_LOGIN }}
          # surge.sh token, generate it with `surge token` command
          token: ${{ secrets.SURGE_TOKEN }}
          # your project path
          project: /home/runner/work/the-vivi-project/the-vivi-project
