name: My Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Website
        run: |
          echo $GITHUB_SHA
          cp -r ./code ./public
          sed -i "s/%%VERSION%%/$GITHUB_SHA/g" ./public/index.html
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./public

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v3
        with:
          name: website
          path: ./public
      - name: Test Artifact
        run: grep "Hello" ./public/index.html

  deploy-review:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: demo
      url: https://fuzzy-coach-$GITHUB_REF_SLUG.surge.sh
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Surge
        run: npm install --global surge
      - uses: actions/download-artifact@v3
        with:
          name: website
          path: ./public
      - name: Deploy to Review Site
        run: surge --project ./public --domain fuzzy-coach-$GITHUB_REF_SLUG.surge.sh
